# Data Science

# Inicialización

In [2]:
import numpy as np
a = np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((3,2,4), dtype=int)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [9]:
np.full((2,2),"helloNato", dtype='<U7')


array([['helloNa', 'helloNa'],
       ['helloNa', 'helloNa']], dtype='<U7')

In [10]:
np.random.rand(10)

array([0.11228463, 0.85025834, 0.14372556, 0.73668352, 0.22246307,
       0.20177648, 0.96875834, 0.28065315, 0.84754523, 0.1919223 ])

In [12]:
data = np.random.randint(5,10,(10,10))
data

array([[7, 8, 7, 9, 9, 8, 6, 7, 7, 8],
       [5, 8, 6, 5, 6, 9, 5, 9, 6, 8],
       [6, 6, 8, 8, 8, 5, 9, 8, 6, 9],
       [6, 6, 7, 8, 5, 7, 5, 7, 6, 8],
       [5, 9, 6, 6, 9, 8, 7, 8, 5, 9],
       [5, 5, 6, 5, 5, 5, 9, 7, 6, 5],
       [8, 6, 5, 7, 8, 5, 9, 9, 7, 8],
       [7, 9, 8, 6, 7, 9, 7, 8, 8, 7],
       [5, 6, 7, 5, 5, 6, 6, 6, 5, 6],
       [6, 6, 9, 7, 6, 7, 6, 5, 9, 5]])

# Acceso a Numpy

In [13]:
data[4:8]

array([[5, 9, 6, 6, 9, 8, 7, 8, 5, 9],
       [5, 5, 6, 5, 5, 5, 9, 7, 6, 5],
       [8, 6, 5, 7, 8, 5, 9, 9, 7, 8],
       [7, 9, 8, 6, 7, 9, 7, 8, 8, 7]])

In [14]:
data[4:8,4:6]

array([[9, 8],
       [5, 5],
       [8, 5],
       [7, 9]])

In [15]:
data[4:6,4:6]

array([[9, 8],
       [5, 5]])

# Combinación de Datos

In [9]:
data1 = np.random.randint(5,15,size=(5,3))
data1

array([[11,  9, 13],
       [ 6, 13, 14],
       [10, 14,  9],
       [ 7, 11,  5],
       [11,  6, 10]])

In [6]:
data2 = np.random.randint(5,15,size=(5,3))
data2

array([[13, 13,  7],
       [ 5,  8, 11],
       [10, 13,  6],
       [10, 11, 12],
       [11, 10,  5]])

In [10]:
np.hstack([data1,data2])

array([[11,  9, 13, 13, 13,  7],
       [ 6, 13, 14,  5,  8, 11],
       [10, 14,  9, 10, 13,  6],
       [ 7, 11,  5, 10, 11, 12],
       [11,  6, 10, 11, 10,  5]])